# Generated by Django 4.2.1 on 2023-06-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
