# Generated by Django 4.2.1 on 2023-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
