# Generated by Django 4.2.2 on 2023-06-13 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_user_resettoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_support",
            fields=[
                ("help_id", models.IntegerField(primary_key=True, serialize=False)),
                ("issue_message", models.TextField()),
                ("image", models.ImageField(upload_to="user_support/images/")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
