# Generated by Django 4.2.2 on 2023-06-13 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_user_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=150)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("specifications_list", models.TextField()),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="seller",
            fields=[
                ("seller_id", models.IntegerField(primary_key=True, serialize=False)),
                ("seller_name", models.CharField(max_length=150)),
                ("seller_email", models.EmailField(max_length=254)),
                ("seller_phone", models.IntegerField()),
                ("seller_password", models.CharField(max_length=30)),
                (
                    "seller_verification_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("seller_verification_slug", models.CharField(max_length=100)),
                ("seller_status", models.CharField(default="active", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="wishlist",
            fields=[
                ("wishlist_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="userAddress",
            fields=[
                ("address_id", models.IntegerField(primary_key=True, serialize=False)),
                ("country", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("street", models.CharField(max_length=30)),
                ("zip_code", models.IntegerField()),
                ("house_no", models.CharField(max_length=40)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sellerAddress",
            fields=[
                ("address_id", models.IntegerField(primary_key=True, serialize=False)),
                ("country", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("street", models.CharField(max_length=30)),
                ("zip_code", models.IntegerField()),
                ("house_no", models.CharField(max_length=40)),
                (
                    "seller_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.seller"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="productReview",
            fields=[
                ("review_id", models.IntegerField(primary_key=True, serialize=False)),
                ("review_msg", models.TextField()),
                ("review_rating", models.IntegerField()),
                ("review_img", models.ImageField(upload_to="")),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="productQuestions",
            fields=[
                ("question_id", models.IntegerField(primary_key=True, serialize=False)),
                ("question_msg", models.TextField()),
                ("answer", models.TextField()),
                ("likes", models.IntegerField()),
                ("dislikes", models.IntegerField()),
                ("replyList", models.TextField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="productImages",
            fields=[
                ("image_id", models.IntegerField(primary_key=True, serialize=False)),
                ("product_image", models.ImageField(upload_to="")),
                ("image_name", models.TextField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="seller_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.seller"
            ),
        ),
        migrations.CreateModel(
            name="orders",
            fields=[
                ("order_id", models.IntegerField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("order_status", models.CharField(max_length=20)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                ("cart_id", models.IntegerField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
