# Generated by Django 4.2.2 on 2023-06-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_product_seller_wishlist_useraddress_selleraddress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_support",
            name="help_id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
