# Generated by Django 4.2.2 on 2023-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_user_support_help_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_support",
            name="help_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
