# Generated by Django 4.2.2 on 2023-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_validity",
            field=models.BooleanField(default=False),
        ),
    ]
