# Generated by Django 4.2.2 on 2023-06-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_user_otp_validity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="resetToken",
            field=models.CharField(default="none", max_length=50),
        ),
    ]
